### ISSUE TITLE
New publication using OGGM

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm.github.io#187]
Ross, A. C., Mendoza, M. M., Drenkhan, F., Montoya, N., Baiker, J. R., Mackay, J. D., Hannah, D. M. and Buytaert, W.: Seasonal water storage and release dynamics of bofedal wetlands in the Central Andes, Hydrol. Process., 37(8), 1–14, doi:10.1002/hyp.14940, 2023.

**Comment by anoukvlug** [comment]
Thanks you for sharing this. I will add it to the publication list :)
