### ISSUE TITLE
New paper(s)

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm.github.io#222]
https://doi.org/10.1016/j.palaeo.2024.112092 

(https://essd.copernicus.org/articles/16/919/2024/ -> this one only uses centerlines. We have many papers now, maybe we can start to distinguish between papers that use OGGM a lot and those who use it only as centerline provider)

**Comment by anoukvlug** [comment]
Yes, it might make sense to make different categories. Lets talk about that during the next meeting.
