### ISSUE TITLE
New publication in review

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm.github.io#230]
Mackay, J. D., Barrand, N. E., Hannah, D. M., Potter, E., Montoya, N., and Buytaert, W.: Physically-based modelling of glacier evolution under climate change in the tropical Andes, EGUsphere [preprint], https://doi.org/10.5194/egusphere-2024-863, 2024.

**Comment by anoukvlug** [comment]
Thanks for the notification @fmaussion :)
