### ISSUE TITLE
New papers - quite a few!

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm.github.io#244]
https://www.sciencedirect.com/science/article/pii/S209592732400673X 

https://www.sciencedirect.com/science/article/pii/S0169555X2400271X

In review:
https://egusphere.copernicus.org/preprints/2024/egusphere-2024-2569/ 
https://egusphere.copernicus.org/preprints/2024/egusphere-2024-757/ (I think they use the data from Muhammad, but still)

**Comment by anoukvlug** [comment]
Thanks for the notification :)
