### ISSUE TITLE
Logo rendering on mobile devices

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm.github.io#7]
The webpage looks OK on mobile, but the logo doesn't :(

**Comment by fmaussion** [comment]
I have solved this by changing to relative coordinates in https://github.com/OGGM/oggm.github.io/pull/16. The logo is quite small on mobile devices: I think there is a relatively easy way in to change the percentage depending on the device we are in. If someone feels bored it is a possible simple project ;)

**Comment by bearecinos** [comment]
I can do this, I already asked .. and found out that is an easy thing to do .. it will be done soonish

**Comment by bearecinos** [comment]
This issue should be close because is fix. I can see the website on my phone and logo size adapts to the window size... we did this I think a while ago
